"""Verify gamification publishes personal SSE events to the saving user
only — never as broadcast.

annotation_saved is broadcast (Paket 7) and reaches all online users; the
gamification events (badge_unlocked, notification) must reach only the
user who triggered them. A subscribed second user should never receive
the personal events generated by another user's actions.
"""
import asyncio

import pytest
from backend.shared.sse import broker as sse_broker


@pytest.fixture(autouse=True)
def _reset_broker():
    sse_broker._subscribers.clear()
    yield
    sse_broker._subscribers.clear()


def _ref(**overrides):
    base = {
        "kanun_no": "5520", "kanun_ad": "KVK", "madde": "5",
        "fikra": "1", "bent": "a", "source_text": "kısa",
    }
    base.update(overrides)
    return base


def test_first_save_badge_only_to_saving_user(second_passed_user, ingest_doc):
    """alice's first save unlocks first_annotation. Bob (online) sees the
    annotation_saved broadcast but NOT badge_unlocked or notification."""
    ctx = second_passed_user
    c = ctx["client"]
    ingest_doc("doc_gam_publ")
    alice_id = ctx["alice"]["id"]
    bob_id = ctx["bob"]["id"]

    bob_q = sse_broker.subscribe(user_id=bob_id)
    alice_q = sse_broker.subscribe(user_id=alice_id)

    ctx["login"]("alice")
    r = c.post("/api/annotations", json={
        "document_id": "doc_gam_publ", "references": [_ref()],
    })
    assert r.status_code == 200

    async def _drain(q, n, timeout=2.0):
        out = []
        for _ in range(n):
            out.append(await asyncio.wait_for(q.get(), timeout=timeout))
        return out

    # alice's queue: annotation_saved (broadcast) + badge_unlocked + notification
    alice_events = asyncio.run(_drain(alice_q, 3))
    types = sorted(e.event_type for e in alice_events)
    assert types == ["annotation_saved", "badge_unlocked", "notification"]

    # bob's queue: only annotation_saved
    bob_events = asyncio.run(_drain(bob_q, 1))
    assert bob_events[0].event_type == "annotation_saved"

    # bob's queue must be empty (no badge or notification leaked)
    async def _empty():
        return await asyncio.wait_for(bob_q.get(), timeout=0.3)
    with pytest.raises(asyncio.TimeoutError):
        asyncio.run(_empty())


def test_review_kept_publishes_only_to_prior_editor(second_passed_user, ingest_doc):
    """bob saves doc; alice edits with same refs (diff_zero) → bob gets the
    review_kept-driven badge events, alice does NOT get bob's badge events
    (alice gets her own first_annotation from her own save)."""
    ctx = second_passed_user
    c = ctx["client"]
    ingest_doc("doc_gam_kept")
    alice_id = ctx["alice"]["id"]
    bob_id = ctx["bob"]["id"]

    ctx["login"]("bob")
    c.post("/api/annotations", json={
        "document_id": "doc_gam_kept", "references": [_ref()],
    })

    bob_q = sse_broker.subscribe(user_id=bob_id)
    alice_q = sse_broker.subscribe(user_id=alice_id)

    ctx["login"]("alice")
    r = c.post("/api/annotations", json={
        "document_id": "doc_gam_kept", "references": [_ref()],  # diff_zero
    })
    assert r.status_code == 200

    # alice receives: annotation_saved (broadcast) + her own first_annotation
    # badge_unlocked + notification
    # bob receives: annotation_saved (broadcast); review_kept does NOT unlock
    # any new badge by itself for bob (bob's first_annotation already unlocked
    # on his earlier save), but the orchestrator may emit zero new events for him.
    # The hard invariant: bob's queue must NOT contain alice's first_annotation
    # badge_unlocked event.
    async def _collect(q, timeout=0.5):
        out = []
        try:
            while True:
                out.append(await asyncio.wait_for(q.get(), timeout=timeout))
        except asyncio.TimeoutError:
            pass
        return out

    alice_events = asyncio.run(_collect(alice_q, 1.0))
    bob_events = asyncio.run(_collect(bob_q, 0.5))

    # bob's annotation_saved is from alice's broadcast; nothing else
    bob_types = [e.event_type for e in bob_events]
    assert bob_types == ["annotation_saved"]

    # alice has her own badge events (first_annotation from her save's ledger row),
    # but we only assert: she sees 'badge_unlocked' and 'notification' — and they
    # describe HER badge, not bob's
    alice_unlock = next((e for e in alice_events if e.event_type == "badge_unlocked"), None)
    assert alice_unlock is not None
    assert alice_unlock.data["badge_id"] == "first_annotation"
