"""v0006 — install the 69 outbox-capture triggers across all 23 in-scope tables.

Triggers fire AFTER INSERT/UPDATE/DELETE on each project table and write a
single `_outbox` row inside the same SQLite transaction as the originating
write. The async dispatcher (backend/mirror/dispatcher.py) drains the queue
and pushes each row to the partner Neon DB.

Generated by `backend.migrations.helpers.trigger_generator.build_all_triggers`
at apply time, so the trigger set always reflects the live SQLite schema.

CRITICAL: We execute each trigger statement individually via `conn.execute`
because `sqlite3.Connection.executescript()` issues an implicit COMMIT that
would prematurely close the runner's `BEGIN IMMEDIATE` transaction.
"""
import sqlite3

from backend.migrations.helpers.trigger_generator import build_all_triggers


def up(conn: sqlite3.Connection) -> None:
    for stmt in build_all_triggers(conn):
        conn.execute(stmt)
